services:
  - type: web
    name: whatsapp-inventory-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
    healthCheckPath: /
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
